# Prerequisites: $DEVHUB_REGISTRY, $DEVHUB_REGISTRY_USERNAME, $DEVHUB_REGISTRY_PASSWORD setup as deployment variables

image: atlassian/default-image:3

definitions:
  services:
    docker:
      memory: 4096

options:
  size: 2x

pipelines:
  branches:
    main:
      - step:
          name: Build And Push
          script:
            - DOCKERFILE_PATH=Dockerfile
            - IMAGE_NAME=${DEVHUB_REGISTRY}/uds-brigade-tracking-ui
            - VERSION="0.1.${BITBUCKET_BUILD_NUMBER}"
            - docker build -f $DOCKERFILE_PATH -t ${IMAGE_NAME}:latest -t ${IMAGE_NAME}:${VERSION} .
            - echo ${DEVHUB_REGISTRY_PASSWORD} | docker login --username $DEVHUB_REGISTRY_USERNAME --password-stdin $DEVHUB_REGISTRY
            - docker push -a ${IMAGE_NAME}
          services:
            - docker
    dev:
      - step:
          name: Build And Push
          script:
            - DOCKERFILE_PATH=Dockerfile
            - IMAGE_NAME=${DEVHUB_REGISTRY}/uds-brigade-tracking-ui
            - VERSION="0.1.${BITBUCKET_BUILD_NUMBER}"
            - docker build -f $DOCKERFILE_PATH -t ${IMAGE_NAME}:latest -t ${IMAGE_NAME}:${VERSION} .
            - echo ${DEVHUB_REGISTRY_PASSWORD} | docker login --username $DEVHUB_REGISTRY_USERNAME --password-stdin $DEVHUB_REGISTRY
            - docker push -a ${IMAGE_NAME}
          services:
            - docker
      - step:
          name: Deploy
          script:
            - STACKFILE_PATH=swarm/init/stack.yml
            - export DOCKER_HOST=${DOCKER_HOST_INIT}
            - export APPLICATION_VERSION="0.1.${BITBUCKET_BUILD_NUMBER}"
            - wget --no-check-certificate --server-response --method POST http://103.init.uz:9000/api/webhooks/671f344b-dd80-4eaa-a8db-b56b005c87ec?tag=$APPLICATION_VERSION
          services:
            - docker